export global Images {
    in property <image> online: @image-url("assets/online.svg");
    in property <image> mine: @image-url("assets/mine.svg");
    in property <image> online_fill: @image-url("assets/online_fill.svg");
    in property <image> mine_fill: @image-url("assets/mine_fill.svg");
    in property <image> file: @image-url("assets/file.svg");
    in property <image> file_gray: @image-url("assets/file_gray.svg");
    in property <image> search: @image-url("assets/search.svg");
    in property <image> close: @image-url("assets/close.svg");
}