
import { Logic } from "./global.slint";
import { FilePicker } from "components/file-picker.slint";
import { RadioGroup } from "components/radio-group.slint";
import { Input } from "components/input.slint";
import { Select } from "components/select.slint";
import { Button } from "components/button.slint";
import { IconButton } from "components/icon-button.slint";
import  {Images } from "./images.slint";



export { Logic }
export component MainWindow inherits Window {
    title: "Components for Slint-UI";
    property <string> select_value: "";
    height: 600px;
    width: 800px;

    VerticalLayout {
        alignment: start;
        spacing: 10px;
        padding: 20px;
        FilePicker { 
            width: 300px;
            height: 40px;
            placeholder: "Choose file";
        }    

        RadioGroup { 
            model: ["u32","u64", "i32", "i64"];
        }

        Input { 
            height: 40px;
            width: 300px;
            prefixText: "￥";
        }

        Select {
            z: 10;
            width: 300px;
            height: 40px;
            value: select_value;
            placeholder: "Single select";
            options: [
                {text:"u32"},
                {text:"u64"},
                {text:"i32"},
                {text:"i64"}
            ];
            change(val) => {
                select-value = val
            }
        }

        Button { 
            z: 1;
            height: 40px;
            width: 100px;
            text: "Submit";
        }

        HorizontalLayout {
            spacing: 10px;
            IconButton { 
                width: 140px;
                height: 100px;
                icon: Images.online-fill;
                icon-pressed: Images.online;
                text: "Communicate";
            }

            IconButton { 
                width: 140px;
                height: 100px;
                selected: true;
                icon: Images.mine-fill;
                icon-pressed: Images.mine;
                text: "Mine";
            }
        }
    }
}